GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Mi nuevo blog",
    "author": "The Memin",
    "url": "www.newblog.com.mx",
    "likes": 300,
    "userId": "687c3cd00cf60e0cd8b68754"
}