GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRoZS1NZW1pbiIsImlkIjoiNjg4N2M4YTE3NzJiOTBjYzUyODhhNzA3IiwiaWF0IjoxNzUzNzI5MjIxLCJleHAiOjE3NTM3MzI4MjF9.oQx1bruv4CqeTbkoOOutp4uuyeVE2911W4p6Op2jI-c

{
    "title": "Blog 1",
    "author": "The-Memin",
    "url": "www.newblog.com.mx",
    "likes": 300
}